### ISSUE TITLE
Incremental Search: Next/Prev

### ISSUE THREAD

**Issue by Figuera** [KoffeinFlummi/htop-vim#11]
I recently updated htop-vim after a long time and was surprised by this:

https://github.com/KoffeinFlummi/htop-vim/commit/f46ddd3230db4a12b319a35a393bf447c613007a

I used this function all the time, why was it removed? And is there an alternative?

**Comment by Figuera** [comment]
Ok, I am suppose to not hit Enter and use F3 and S-F3.

It took me a while to figure it out (even though there was a helper message on the side).  I am still curious why the feature was removed though. 

If I were to recreated it what lines should I change? I tried adding the old `actionIncNext` function but that is not working.

**Comment by KoffeinFlummi** [comment]
Sorry for the late reply. The change was made upstream, in the main htop repo: https://github.com/htop-dev/htop. I would suggest modifying this constant, but I haven't tried it myself: https://github.com/KoffeinFlummi/htop-vim/blob/master/IncSet.c#L40
