### ISSUE TITLE
Tags needed

### ISSUE THREAD

**Issue by aiotter** [KoffeinFlummi/htop-vim#4]
I'm a heavy user of htop-vim and want it to be installed via homebrew (package manager for macOS).
I've created [the file needed](https://github.com/aiotter/homebrew-htop-vim), but I found I cannot make a PR to homebrew with it, as they do not accept a script to install a project with no stable release (or a tag).
If you set a tag to your latest release of the project, I will write the tag to the file and create a PR to homebrew, so that htop-vim can be installed with it.
Please consider to set a tag to your project!

**Comment by KoffeinFlummi** [comment]
Sorry for the late reply. I usually only update this repo once the patch in [this PKGBUILD](https://aur.archlinux.org/packages/htop-vim-git/) stops applying, but I created a tag [here](https://github.com/KoffeinFlummi/htop-vim/releases/tag/3.0.2vim).

Let me know if that doesn't suffice. I'll try to remember to keep the tags updated with the upstream ones, but feel free to tag or message me if I forget.
